import type { Metadata } from "next";
import { FadeIn } from "@/components/marketing/fade-in";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Co-Founder.ai terms of service. The legal agreement governing your use of our platform.",
};

export default function TermsPage() {
  return (
    <section className="pt-32 pb-24 lg:pt-40 lg:pb-32">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <FadeIn>
          <h1 className="text-4xl sm:text-5xl font-bold tracking-tight mb-4">
            Terms of Service
          </h1>
          <p className="text-white/40 text-sm mb-12">
            Last updated: February 15, 2026
          </p>
        </FadeIn>

        <div className="prose-invert space-y-10">
          <FadeIn delay={0.05}>
            <section>
              <h2 className="text-xl font-bold mb-3">1. Acceptance of Terms</h2>
              <p className="text-sm text-white/50 leading-relaxed">
                By accessing or using Co-Founder.ai (&ldquo;the Service&rdquo;), you agree to be
                bound by these Terms of Service. If you do not agree with any part of these
                terms, you may not use the Service. These terms apply to all users, visitors,
                and others who access or use the Service.
              </p>
            </section>
          </FadeIn>

          <FadeIn delay={0.08}>
            <section>
              <h2 className="text-xl font-bold mb-3">2. Description of Service</h2>
              <p className="text-sm text-white/50 leading-relaxed">
                Co-Founder.ai provides an AI-powered autonomous development platform that
                generates code, runs tests, and assists with software deployment. The Service
                is provided &ldquo;as is&rdquo; and we continuously work to improve its capabilities
                and reliability.
              </p>
            </section>
          </FadeIn>

          <FadeIn delay={0.11}>
            <section>
              <h2 className="text-xl font-bold mb-3">3. Intellectual Property</h2>
              <p className="text-sm text-white/50 leading-relaxed mb-3">
                You retain full ownership of all code, content, and intellectual property
                generated through your use of the Service. Co-Founder.ai does not claim any
                ownership rights over your projects, code, or data.
              </p>
              <p className="text-sm text-white/50 leading-relaxed">
                The Co-Founder.ai platform, including its design, features, documentation,
                and underlying technology, remains the intellectual property of Co-Founder.ai.
              </p>
            </section>
          </FadeIn>

          <FadeIn delay={0.14}>
            <section>
              <h2 className="text-xl font-bold mb-3">4. User Responsibilities</h2>
              <p className="text-sm text-white/50 leading-relaxed">
                You are responsible for maintaining the security of your account credentials,
                reviewing and testing code generated by the Service before deploying it to
                production, ensuring that your use of the Service complies with applicable laws,
                and not using the Service to generate malicious software, violate third-party
                rights, or engage in illegal activities.
              </p>
            </section>
          </FadeIn>

          <FadeIn delay={0.17}>
            <section>
              <h2 className="text-xl font-bold mb-3">5. Payments and Billing</h2>
              <p className="text-sm text-white/50 leading-relaxed">
                Paid plans are billed on a recurring basis (monthly or annually). You can
                cancel at any time, and your subscription will remain active until the end
                of the current billing period. Refunds are handled on a case-by-case basis.
                We reserve the right to modify pricing with 30 days advance notice.
              </p>
            </section>
          </FadeIn>

          <FadeIn delay={0.2}>
            <section>
              <h2 className="text-xl font-bold mb-3">6. Service Availability</h2>
              <p className="text-sm text-white/50 leading-relaxed">
                We strive for 99.9% uptime but do not guarantee uninterrupted access.
                Scheduled maintenance windows will be communicated in advance. We are not
                liable for downtime caused by factors outside our control, including
                third-party service outages, network issues, or force majeure events.
              </p>
            </section>
          </FadeIn>

          <FadeIn delay={0.23}>
            <section>
              <h2 className="text-xl font-bold mb-3">7. Limitation of Liability</h2>
              <p className="text-sm text-white/50 leading-relaxed">
                To the maximum extent permitted by law, Co-Founder.ai shall not be liable
                for any indirect, incidental, special, consequential, or punitive damages
                arising from your use of the Service. Our total liability shall not exceed
                the amount you paid us in the 12 months preceding the claim.
              </p>
            </section>
          </FadeIn>

          <FadeIn delay={0.26}>
            <section>
              <h2 className="text-xl font-bold mb-3">8. Code Quality Disclaimer</h2>
              <p className="text-sm text-white/50 leading-relaxed">
                While we strive to generate high-quality, production-ready code, AI-generated
                code should be reviewed and tested before deployment. You acknowledge that
                automated code generation may contain errors and that you are responsible for
                validating all output before use in production environments.
              </p>
            </section>
          </FadeIn>

          <FadeIn delay={0.29}>
            <section>
              <h2 className="text-xl font-bold mb-3">9. Termination</h2>
              <p className="text-sm text-white/50 leading-relaxed">
                We may terminate or suspend your account if you violate these terms.
                Upon termination, you retain ownership of your code and data, and may
                request a full export within 30 days of account closure.
              </p>
            </section>
          </FadeIn>

          <FadeIn delay={0.32}>
            <section>
              <h2 className="text-xl font-bold mb-3">10. Changes to Terms</h2>
              <p className="text-sm text-white/50 leading-relaxed">
                We may modify these terms at any time. Material changes will be communicated
                via email at least 30 days before they take effect. Continued use of the
                Service after changes take effect constitutes acceptance of the new terms.
              </p>
            </section>
          </FadeIn>

          <FadeIn delay={0.35}>
            <section>
              <h2 className="text-xl font-bold mb-3">11. Contact</h2>
              <p className="text-sm text-white/50 leading-relaxed">
                For questions about these terms, contact us at legal@getinsourced.ai.
              </p>
            </section>
          </FadeIn>
        </div>
      </div>
    </section>
  );
}
