"""add understanding_sessions table

Revision ID: 1cbc4ccfd46b
Revises: bb0bc73fe207
Create Date: 2026-02-17 12:57:24.457243

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1cbc4ccfd46b'
down_revision: str | Sequence[str] | None = 'bb0bc73fe207'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create understanding_sessions table
    op.create_table(
        'understanding_sessions',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
        sa.Column('onboarding_session_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('current_question_index', sa.Integer(), nullable=False),
        sa.Column('total_questions', sa.Integer(), nullable=False),
        sa.Column('questions', sa.JSON(), nullable=False),
        sa.Column('answers', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['onboarding_session_id'], ['onboarding_sessions.id'], ),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_understanding_sessions_clerk_user_id'), 'understanding_sessions', ['clerk_user_id'], unique=False)

    # ### commands auto generated by Alembic - please adjust! ###
    # Skip dropping episodes table and other unrelated changes - those were already applied
    # Only keep understanding_sessions table creation
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop understanding_sessions table
    op.drop_index(op.f('ix_understanding_sessions_clerk_user_id'), table_name='understanding_sessions')
    op.drop_table('understanding_sessions')
