"""add stripe_webhook_events table

Revision ID: 892d2f2ce669
Revises: 978ccdb48f58
Create Date: 2026-02-19 06:40:40.914247

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "892d2f2ce669"
down_revision: str | Sequence[str] | None = "978ccdb48f58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stripe_webhook_events",
        sa.Column("event_id", sa.String(length=255), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.drop_index(op.f("ix_episodes_project_id"), table_name="episodes")
    op.drop_index(op.f("ix_episodes_session_id"), table_name="episodes")
    op.drop_index(op.f("ix_episodes_user_id"), table_name="episodes")
    op.drop_table("episodes")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "episodes",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("project_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("session_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("goal", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("plan", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("steps_completed", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("total_steps", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("errors", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("final_error", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("files_created", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("commit_sha", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("pr_url", sa.VARCHAR(length=512), autoincrement=False, nullable=True),
        sa.Column("started_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("completed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("extra_data", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("episodes_pkey")),
    )
    op.create_index(op.f("ix_episodes_user_id"), "episodes", ["user_id"], unique=False)
    op.create_index(op.f("ix_episodes_session_id"), "episodes", ["session_id"], unique=False)
    op.create_index(op.f("ix_episodes_project_id"), "episodes", ["project_id"], unique=False)
    op.drop_table("stripe_webhook_events")
    # ### end Alembic commands ###
