"""add onboarding_sessions table

Revision ID: b2a5eef209b4
Revises: 6a8f3f01a56b
Create Date: 2026-02-16 22:35:26.414240

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2a5eef209b4"
down_revision: str | Sequence[str] | None = "6a8f3f01a56b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create onboarding_sessions table
    op.create_table(
        "onboarding_sessions",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("clerk_user_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("current_question_index", sa.Integer(), nullable=False),
        sa.Column("total_questions", sa.Integer(), nullable=False),
        sa.Column("idea_text", sa.Text(), nullable=False),
        sa.Column("questions", sa.JSON(), nullable=False),
        sa.Column("answers", sa.JSON(), nullable=False),
        sa.Column("thesis_snapshot", sa.JSON(), nullable=True),
        sa.Column("thesis_edits", sa.JSON(), nullable=True),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_onboarding_sessions_clerk_user_id"), "onboarding_sessions", ["clerk_user_id"], unique=False
    )

    op.drop_index(op.f("ix_episodes_project_id"), table_name="episodes")
    op.drop_index(op.f("ix_episodes_session_id"), table_name="episodes")
    op.drop_index(op.f("ix_episodes_user_id"), table_name="episodes")
    op.drop_table("episodes")
    op.add_column("projects", sa.Column("stage_number", sa.Integer(), nullable=True))
    op.add_column("projects", sa.Column("stage_entered_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("projects", sa.Column("progress_percent", sa.Integer(), nullable=False))
    op.alter_column(
        "projects",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "projects",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.add_column("user_settings", sa.Column("email", sa.String(length=255), nullable=True))
    op.add_column("user_settings", sa.Column("name", sa.String(length=255), nullable=True))
    op.add_column("user_settings", sa.Column("avatar_url", sa.String(length=500), nullable=True))
    op.add_column("user_settings", sa.Column("company_name", sa.String(length=255), nullable=True))
    op.add_column("user_settings", sa.Column("role", sa.String(length=100), nullable=True))
    op.add_column("user_settings", sa.Column("timezone", sa.String(length=100), nullable=True))
    op.add_column("user_settings", sa.Column("onboarding_completed", sa.Boolean(), nullable=False))
    op.add_column("user_settings", sa.Column("beta_features", sa.JSON(), nullable=True))
    op.alter_column(
        "user_settings",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "user_settings",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop onboarding_sessions table
    op.drop_index(op.f("ix_onboarding_sessions_clerk_user_id"), table_name="onboarding_sessions")
    op.drop_table("onboarding_sessions")

    op.alter_column(
        "user_settings",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "user_settings",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_column("user_settings", "beta_features")
    op.drop_column("user_settings", "onboarding_completed")
    op.drop_column("user_settings", "timezone")
    op.drop_column("user_settings", "role")
    op.drop_column("user_settings", "company_name")
    op.drop_column("user_settings", "avatar_url")
    op.drop_column("user_settings", "name")
    op.drop_column("user_settings", "email")
    op.alter_column(
        "projects",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "projects",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_column("projects", "progress_percent")
    op.drop_column("projects", "stage_entered_at")
    op.drop_column("projects", "stage_number")
    op.create_table(
        "episodes",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("project_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("session_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("goal", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("plan", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("steps_completed", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("total_steps", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("errors", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("final_error", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("files_created", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("commit_sha", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("pr_url", sa.VARCHAR(length=512), autoincrement=False, nullable=True),
        sa.Column("started_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("completed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("extra_data", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("episodes_pkey")),
    )
    op.create_index(op.f("ix_episodes_user_id"), "episodes", ["user_id"], unique=False)
    op.create_index(op.f("ix_episodes_session_id"), "episodes", ["session_id"], unique=False)
    op.create_index(op.f("ix_episodes_project_id"), "episodes", ["project_id"], unique=False)
    # ### end Alembic commands ###
